name: 'GitHub Pages'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dwenegar/setup-lua@master
        with:
          lua-version: '5.4'
          luarocks-version: latest
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          luarocks install ldoc
          ldoc -c build-aux/config.ld .
      - name: deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
